// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const howItWorksContainer: string;
export const sectionImageContainer: string;
export const honeyImage: string;
