// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navContainer: string;
export const logoContainer: string;
export const isSticky: string;
export const quickLinks: string;
export const hamburgerOutline: string;
export const overlayContainer: string;
export const mobileNavContainer: string;
export const quickLinksMobile: string;
