// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const ghost: string;
export const dissolve: string;
export const outline: string;
export const inverted: string;
export const communityLink: string;
export const hero: string;
