// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const heroContainer: string;
export const heading: string;
export const subText: string;
export const heroContent: string;
export const imageContainer: string;
